<a href="https://colab.research.google.com/github/suraj4502/Python_code/blob/main/EDA_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Label Encoder

In [5]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd

In [6]:
data =pd.read_csv("/content/Iris.csv",index_col=0)

In [7]:
data.head()

              sepal width  petal length  petal width         iris
sepal length
5.1                   3.5           1.4          0.2  Iris-setosa
4.9                   3.0           1.4          0.2  Iris-setosa
4.7                   3.2           1.3          0.2  Iris-setosa
4.6                   3.1           1.5          0.2  Iris-setosa
5.0                   3.6           1.4          0.2  Iris-setosa

In [8]:
#Changes does not effect the "data" dataframe
data1=data.copy()

In [6]:
labelencoder = LabelEncoder()
data1.iloc[:, -1] = labelencoder.fit_transform(data1.iloc[:,-1])

In [7]:
data1

              sepal width  petal length  petal width  iris
sepal length
5.1                   3.5           1.4          0.2     0
4.9                   3.0           1.4          0.2     0
4.7                   3.2           1.3          0.2     0
4.6                   3.1           1.5          0.2     0
5.0                   3.6           1.4          0.2     0
...                   ...           ...          ...   ...
6.7                   3.0           5.2          2.3     2
6.3                   2.5           5.0          1.9     2
6.5                   3.0           5.2          2.0     2
6.2                   3.4           5.4          2.3     2
5.9                   3.0           5.1          1.8     2

[150 rows x 4 columns]

### One Hot Encoder

#### Using sklearn

In [8]:
from sklearn.preprocessing import OneHotEncoder

In [9]:
data2=pd.read_csv("/content/Iris.csv",index_col=0)

In [10]:
data2

              sepal width  petal length  petal width            iris
sepal length
5.1                   3.5           1.4          0.2     Iris-setosa
4.9                   3.0           1.4          0.2     Iris-setosa
4.7                   3.2           1.3          0.2     Iris-setosa
4.6                   3.1           1.5          0.2     Iris-setosa
5.0                   3.6           1.4          0.2     Iris-setosa
...                   ...           ...          ...             ...
6.7                   3.0           5.2          2.3  Iris-virginica
6.3                   2.5           5.0          1.9  Iris-virginica
6.5                   3.0           5.2          2.0  Iris-virginica
6.2                   3.4           5.4          2.3  Iris-virginica
5.9                   3.0           5.1          1.8  Iris-virginica

[150 rows x 4 columns]

In [11]:
# creating instance of one-hot-encoder
enc = OneHotEncoder(handle_unknown='ignore')

In [14]:
# passing bridge-types-cat column (label encoded values of bridge_types)
enc_df = pd.DataFrame(enc.fit_transform(data2[['iris']]).toarray())

In [15]:
enc_df

       0    1    2
0    1.0  0.0  0.0
1    1.0  0.0  0.0
2    1.0  0.0  0.0
3    1.0  0.0  0.0
4    1.0  0.0  0.0
..   ...  ...  ...
145  0.0  0.0  1.0
146  0.0  0.0  1.0
147  0.0  0.0  1.0
148  0.0  0.0  1.0
149  0.0  0.0  1.0

[150 rows x 3 columns]

In [23]:
data2=pd.DataFrame(data2)

In [26]:
# merge with main df 
data_final = data2.iloc[:,0:4].join(enc_df)
data_final

     sepal width  petal length  petal width            iris   0   1   2
4.3          3.0           1.1          0.1     Iris-setosa NaN NaN NaN
4.4          2.9           1.4          0.2     Iris-setosa NaN NaN NaN
4.4          3.0           1.3          0.2     Iris-setosa NaN NaN NaN
4.4          3.2           1.3          0.2     Iris-setosa NaN NaN NaN
4.5          2.3           1.3          0.3     Iris-setosa NaN NaN NaN
..           ...           ...          ...             ...  ..  ..  ..
7.7          3.8           6.7          2.2  Iris-virginica NaN NaN NaN
7.7          2.6           6.9          2.3  Iris-virginica NaN NaN NaN
7.7          2.8           6.7          2.0  Iris-virginica NaN NaN NaN
7.7          3.0           6.1          2.3  Iris-virginica NaN NaN NaN
7.9          3.8           6.4          2.0  Iris-virginica NaN NaN NaN

[150 rows x 7 columns]

#### Using Pandas

In [27]:
import pandas as pd

In [29]:
data3 =pd.read_csv("/content/Iris.csv",index_col=0)

In [30]:
data_encoded=pd.get_dummies(data3)

In [31]:
data_encoded

              sepal width  ...  iris_Iris-virginica
sepal length               ...
5.1                   3.5  ...                    0
4.9                   3.0  ...                    0
4.7                   3.2  ...                    0
4.6                   3.1  ...                    0
5.0                   3.6  ...                    0
...                   ...  ...                  ...
6.7                   3.0  ...                    1
6.3                   2.5  ...                    1
6.5                   3.0  ...                    1
6.2                   3.4  ...                    1
5.9                   3.0  ...                    1

[150 rows x 6 columns]

#### IsolationForest

In [32]:
from sklearn.ensemble import IsolationForest

In [34]:
data =pd.read_csv("/content/Iris.csv",index_col=0)
data_encoded=pd.get_dummies(data)

In [36]:
# training the model
clf = IsolationForest(random_state=10,contamination=.01)
clf.fit(data_encoded)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  "X does not have valid feature names, but"

IsolationForest(contamination=0.01, random_state=10)

In [37]:
# predictions
y_pred_outliers = clf.predict(data_encoded)

In [38]:
#-1 for outliers and 1 for inliers.
y_pred_outliers

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

In [39]:
data_encoded

              sepal width  ...  iris_Iris-virginica
sepal length               ...
5.1                   3.5  ...                    0
4.9                   3.0  ...                    0
4.7                   3.2  ...                    0
4.6                   3.1  ...                    0
5.0                   3.6  ...                    0
...                   ...  ...                  ...
6.7                   3.0  ...                    1
6.3                   2.5  ...                    1
6.5                   3.0  ...                    1
6.2                   3.4  ...                    1
5.9                   3.0  ...                    1

[150 rows x 6 columns]

In [46]:
## Let us add a new data point which is outlier
data_encoded.loc[150]=[20,40,30,50,1,0,0]

In [47]:
data_encoded

              sepal width  petal length  ...  iris_Iris-virginica    scores
sepal length                             ...
5.1                   3.5           1.4  ...                    0  0.204395
4.9                   3.0           1.4  ...                    0  0.187227
4.7                   3.2           1.3  ...                    0  0.183107
4.6                   3.1           1.5  ...                    0  0.186016
5.0                   3.6           1.4  ...                    0  0.193754
...                   ...           ...  ...                  ...       ...
6.3                   2.5           5.0  ...                    1  0.127949
6.5                   3.0           5.2  ...                    1  0.159608
6.2                   3.4           5.4  ...                    1  0.096144
5.9                   3.0           5.1  ...                    1  0.170129
150.0                20.0          40.0  ...                    0  0.000000

[151 rows x 7 columns]

In [48]:
# training the model
clf = IsolationForest(random_state=10,contamination=.01)
clf.fit(data_encoded)
# predictions
y_pred_outliers = clf.predict(data_encoded)
y_pred_outliers

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  "X does not have valid feature names, but"

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1])

In [49]:
data_encoded['scores']=clf.decision_function(data_encoded)

In [45]:
data_encoded

              sepal width  petal length  ...  iris_Iris-virginica    scores
sepal length                             ...
5.1                   3.5           1.4  ...                    0  0.204395
4.9                   3.0           1.4  ...                    0  0.187227
4.7                   3.2           1.3  ...                    0  0.183107
4.6                   3.1           1.5  ...                    0  0.186016
5.0                   3.6           1.4  ...                    0  0.193754
...                   ...           ...  ...                  ...       ...
6.7                   3.0           5.2  ...                    1  0.142477
6.3                   2.5           5.0  ...                    1  0.127949
6.5                   3.0           5.2  ...                    1  0.159608
6.2                   3.4           5.4  ...                    1  0.096144
5.9                   3.0           5.1  ...                    1  0.170129

[150 rows x 7 columns]

In [50]:
data_encoded['anomaly']=clf.predict(data_encoded.iloc[:,0:7])

In [51]:
data_encoded

              sepal width  petal length  ...    scores  anomaly
sepal length                             ...
5.1                   3.5           1.4  ...  0.176832        1
4.9                   3.0           1.4  ...  0.176190        1
4.7                   3.2           1.3  ...  0.172487        1
4.6                   3.1           1.5  ...  0.186807        1
5.0                   3.6           1.4  ...  0.173457        1
...                   ...           ...  ...       ...      ...
6.3                   2.5           5.0  ...  0.129803        1
6.5                   3.0           5.2  ...  0.174195        1
6.2                   3.4           5.4  ...  0.113812        1
5.9                   3.0           5.1  ...  0.160917        1
150.0                20.0          40.0  ... -0.272286       -1

[151 rows x 8 columns]

In [52]:
#Print the outlier data points
data_encoded[data_encoded['anomaly']==-1]

              sepal width  petal length  ...    scores  anomaly
sepal length                             ...
7.7                   2.6           6.9  ... -0.000586       -1
6.0                   2.2           5.0  ...  0.000586       -1
150.0                20.0          40.0  ... -0.272286       -1

[3 rows x 8 columns]

### PPS score

In [ ]:
#install the package
!pip install ppscore

In [10]:
import ppscore as pps

In [25]:
data.rename({'sepal length':'sl','petal length':'pl'},axis=1,inplace=True)

In [29]:
data1=pd.read_csv('/content/iris.csv')
data1

     Unnamed: 0  Sepal.Length  ...  Petal.Width    Species
0             1           5.1  ...          0.2     setosa
1             2           4.9  ...          0.2     setosa
2             3           4.7  ...          0.2     setosa
3             4           4.6  ...          0.2     setosa
4             5           5.0  ...          0.2     setosa
..          ...           ...  ...          ...        ...
145         146           6.7  ...          2.3  virginica
146         147           6.3  ...          1.9  virginica
147         148           6.5  ...          2.0  virginica
148         149           6.2  ...          2.3  virginica
149         150           5.9  ...          1.8  virginica

[150 rows x 6 columns]

In [32]:
#pps.score(df, "feature_column", "target_column")  syntax
pps.score(data1, "Sepal.Length", "Petal.Length")

{'baseline_score': 1.4886666666666668,
 'case': 'regression',
 'is_valid_score': True,
 'metric': 'mean absolute error',
 'model': DecisionTreeRegressor(),
 'model_score': 0.6692708968366863,
 'ppscore': 0.550422595049248,
 'x': 'Sepal.Length',
 'y': 'Petal.Length'}

In [33]:
#calculate the whole PPS matrix
pps.matrix(data1)

               x             y  ...  model_score                     model
0     Unnamed: 0    Unnamed: 0  ...     1.000000                      None
1     Unnamed: 0  Sepal.Length  ...     0.546302   DecisionTreeRegressor()
2     Unnamed: 0   Sepal.Width  ...     0.351938   DecisionTreeRegressor()
3     Unnamed: 0  Petal.Length  ...     0.466518   DecisionTreeRegressor()
4     Unnamed: 0   Petal.Width  ...     0.229001   DecisionTreeRegressor()
5     Unnamed: 0       Species  ...     0.986643  DecisionTreeClassifier()
6   Sepal.Length    Unnamed: 0  ...    28.607972   DecisionTreeRegressor()
7   Sepal.Length  Sepal.Length  ...     1.000000                      None
8   Sepal.Length   Sepal.Width  ...     0.364704   DecisionTreeRegressor()
9   Sepal.Length  Petal.Length  ...     0.669271   DecisionTreeRegressor()
10  Sepal.Length   Petal.Width  ...     0.366339   DecisionTreeRegressor()
11  Sepal.Length       Species  ...     0.658333  DecisionTreeClassifier()
12   Sepal.Width    Unnamed: 0  ...    34.229701   DecisionTreeRegressor()
13   Sepal.Width  Sepal.Length  ...     0.679897   DecisionTreeRegressor()
14   Sepal.Width   Sepal.Width  ...     1.000000                      None
15   Sepal.Width  Petal.Length  ...     1.232058   DecisionTreeRegressor()
16   Sepal.Width   Petal.Width  ...     0.559017   DecisionTreeRegressor()
17   Sepal.Width       Species  ...     0.454805  DecisionTreeClassifier()
18  Petal.Length    Unnamed: 0  ...    16.675354   DecisionTreeRegressor()
19  Petal.Length  Sepal.Length  ...     0.324794   DecisionTreeRegressor()
20  Petal.Length   Sepal.Width  ...     0.313427   DecisionTreeRegressor()
21  Petal.Length  Petal.Length  ...     1.000000                      None
22  Petal.Length   Petal.Width  ...     0.164425   DecisionTreeRegressor()
23  Petal.Length       Species  ...     0.925512  DecisionTreeClassifier()
24   Petal.Width    Unnamed: 0  ...    15.927291   DecisionTreeRegressor()
25   Petal.Width  Sepal.Length  ...     0.421816   DecisionTreeRegressor()
26   Petal.Width   Sepal.Width  ...     0.246474   DecisionTreeRegressor()
27   Petal.Width  Petal.Length  ...     0.300302   DecisionTreeRegressor()
28   Petal.Width   Petal.Width  ...     1.000000                      None
29   Petal.Width       Species  ...     0.953215  DecisionTreeClassifier()
30       Species    Unnamed: 0  ...    12.550092   DecisionTreeRegressor()
31       Species  Sepal.Length  ...     0.404204   DecisionTreeRegressor()
32       Species   Sepal.Width  ...     0.266416   DecisionTreeRegressor()
33       Species  Petal.Length  ...     0.319479   DecisionTreeRegressor()
34       Species   Petal.Width  ...     0.157460   DecisionTreeRegressor()
35       Species       Species  ...     1.000000                      None

[36 rows x 9 columns]